import React from 'react';

export default function About() {
  return (
    <div className="about-container">
      <h1>About This Project</h1>
      <p>
        This project was created by Henry Do. The motivation behind this project was to address the limitations of modern resume generators for engineering professions. Many existing tools produced unprofessional-looking resumes that didn't meet the high standards required in the engineering field. Additionally, manually editing LaTeX templates can be exhausting and time-consuming.
      </p>
      <p>
        By creating this project, Henry aimed to provide a more professional and user-friendly solution for generating engineering resumes. This tool allows users to easily create and customize their resumes without compromising on quality or appearance.
      </p>

      <hr className="divider" />

      <h2>FAQ</h2>
      
      <h3>How can I contact about bugs or issues?</h3>
      <p>
        If you encounter any bugs or issues, please report them on the project's <a href="https://github.com/Ori2846/ResumeGenerator/issues" target="_blank" rel="noopener noreferrer">GitHub Issues page</a>. You can also contact Henry directly through the Contact section.
      </p>

      <h3>How can I add my own template?</h3>
      <p>
        Adding your own template is currently a work in progress. We are working hard to provide this feature in a future update. Please stay tuned for more updates.
      </p>

      <h3>Why was this project created?</h3>
      <p>
        This project was created to solve the problem of unprofessional-looking resumes generated by existing tools for engineering professions. It aims to provide a more polished and customizable solution without the hassle of manually editing LaTeX templates.
      </p>

      <h3>Can I contribute to this project?</h3>
      <p>
        Yes, contributions are welcome! If you'd like to contribute, please visit the <a href="https://github.com/Ori2846/ResumeGenerator" target="_blank" rel="noopener noreferrer">GitHub repository</a> for more information on how to get started.
      </p>
    </div>
  );
}
