name: LaTeX to PDF

on:
  push:
    branches:
      - '**'  # Listen to all branches
  pull_request:
    branches:
      - '**'  # Listen to all branches
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache LaTeX packages
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-texlive-

    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full --fix-missing

    - name: Compile LaTeX to PDF
      run: |
        mkdir -p output
        pdflatex -interaction=nonstopmode -output-directory=output NextJS-App/resgen/public/file.tex
    
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: NextJS-App/resgen/output/file.pdf
