name: LaTeX to PDF

on:
  push:
    branches:
      - '**'  # Listen to all branches
  pull_request:
    branches:
      - '**'  # Listen to all branches
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update package list and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full --fix-missing

    - name: Compile LaTeX to PDF
      run: |
        mkdir output
        pdflatex -interaction=nonstopmode -output-directory=output NextJS-App/resgen/public/file.tex
    
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: NextJS-App/resgen/output/file.pdf
