name: Generate PDF with XeLaTeX

on:
  workflow_dispatch:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: v2
        fetch-depth: 1  # Shallow clone

    - name: Cache LaTeX intermediate files
      id: cache-latex
      uses: actions/cache@v3
      with:
        path: NextJS-App/resgen/uploads
        key: ${{ runner.os }}-latex-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-latex-

    - name: Ensure upload directory exists
      run: |
        if ($env:RUNNER_OS -eq 'Windows') {
          if (-Not (Test-Path -Path 'NextJS-App\resgen\uploads')) {
            New-Item -ItemType Directory -Path 'NextJS-App\resgen\uploads'
          }
        } else {
          mkdir -p NextJS-App/resgen/uploads
        }

    - name: Compile LaTeX to PDF
      run: |
        if ($env:RUNNER_OS -eq 'Windows') {
          cd NextJS-App\resgen\uploads
          xelatex -interaction=nonstopmode resume_output.tex; if ($LastExitCode -ne 0) { exit 0 }
        } else {
          cd NextJS-App/resgen/uploads
          xelatex -interaction=nonstopmode resume_output.tex; if ($LastExitCode -ne 0) { exit 0 }

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: NextJS-App/resgen/uploads/resume_output.pdf
